variables:
  GIT_DEPTH: 1
stages:
  - deploy
# build_and_push_dev:
#   stage: build
#   image: docker:stable
#   services:
#     - docker:dind
#   variables:
#     DOCKER_HOST: tcp://docker:2375
#     DOCKER_DRIVER: overlay2
#   before_script:
    # - apk add --no-cache curl git-secret
#   script:
#     - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
#   only:
#     - develop
deploy_dev:
  stage: deploy
  tags:
    - dev-runner-01
  image: quay.io/sighup/kubectl-kustomize:1.18.2_3.6.1
  before_script:
    - echo @testing http://nl.alpinelinux.org/alpine/edge/testing >> /etc/apk/repositories
    - apk update
    - apk add gawk git git-secret@testing ca-certificates gnupg bash
    - echo $GITLAB_PRIVATE_KEY
    - echo $GPG_PASSPHRASE
    - echo $GITLAB_PRIVATE_KEY | awk '{gsub(/\\n/,"\n")}1' > /tmp/gpg.key
    - echo $GPG_PASSPHRASE | gpg --batch --yes --passphrase-fd 0  --import /tmp/gpg.key
    - git secret reveal -f -p $GPG_PASSPHRASE
    - cd kubernetes/dev
  script:
    - kustomize build
    # - kustomize edit set imagetag 074358058669.dkr.ecr.eu-west-1.amazonaws.com/test:$CI_COMMIT_SHORT_SHA
    - kustomize build | kubectl apply -f -
