apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: couchbase

bases:
  - ../../bases

patchesStrategicMerge:
  - patches/nodeselector.yaml

patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: couchbase-sdk-gateway
      namespace: couchbase
    path: patches/deployment.yml

secretGenerator:
  - name: cb-sdk-gateway-common
    namespace: couchbase
    envs:
      - secrets/cb-sdk-gateway-common.env
