apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: couchbase

bases:
  - ../base

nameSuffix: -twf-20009-prod

commonLabels:
  bucket: twf-20009-prod

patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: couchbase-sdk-gateway-twf-20009-prod
      namespace: couchbase
    path: patches/deployment.yml

secretGenerator:
  - name: cb-sdk-gateway-twf-20009-prod
    namespace: couchbase
    envs:
      - secrets/cb-sdk-gateway-twf-20009-prod.env
