- op: replace
  path: /spec/template/spec/containers/0/resources
  value:
    limits:
      cpu: "400m"
      memory: "600Mi"
    requests:
      cpu: "100m"
      memory: "100Mi"

- op: add
  path: /spec/template/spec/containers/0/envFrom/1
  value:
    secretRef:
      name: cb-sdk-gateway-twf-20009-prod
