apiVersion: apps/v1
kind: Deployment
metadata:
  name: couchbase-sdk-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: couchbase-sdk-gateway
  template:
    metadata:
      labels:
        app: couchbase-sdk-gateway
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - couchbase
            topologyKey: "kubernetes.io/hostname"
      containers:
        - name: app
          image: registry.gitlab.com/mobilebridgesrl/cloud/cloudservice/couchbase-sdk-gateway:latest
          imagePullPolicy: Always
          envFrom: []
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
          resources:
            limits:
              cpu: "200m"
              memory: "500Mi"
            requests:
              cpu: "100m"
              memory: "100Mi"
      imagePullSecrets:
        - name: gitlab-registry
