kind: Service
apiVersion: v1
metadata:
  name: couchbase-sdk-gateway-balancer
  labels:
    app: couchbase-sdk-gateway
spec:
  selector:
    app: couchbase-sdk-gateway
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  type: NodePort
